"""Removed FK from task_id

Revision ID: 440350a995fc
Revises: 9a3b0ab80615
Create Date: 2023-11-19 06:17:05.310961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "440350a995fc"
down_revision = "9a3b0ab80615"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("task_history_task_id_fkey", "task_history", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "task_history_task_id_fkey", "task_history", "task", ["task_id"], ["id"]
    )
    # ### end Alembic commands ###
